default:
	g++ -Wall -I/usr/include/mysql-cppconn -ologin login.cpp -L/usr/lib -lmysqlcppconn -lcrypto
	g++ -Wall -I/usr/include/mysql-cppconn -ologout logout.cpp -L/usr/lib -lmysqlcppconn
	g++ -Wall -I/usr/include/mysql-cppconn -oHome Home.cpp -L/usr/lib -lmysqlcppconn
	g++ -Wall -I/usr/include/mysql-cppconn -osign_up SignUp.cpp -L/usr/lib -lmysqlcppconn -lcrypto
	g++ -Wall -I/usr/include/mysql-cppconn -oadd_product AddProduct.cpp -L/usr/lib -lmysqlcppconn
	g++ -Wall -I/usr/include/mysql-cppconn -oadd_claim AddClaim.cpp -L/usr/lib -lmysqlcppconn
	g++ -Wall -I/usr/include/mysql-cppconn -oadd_to_cart AddToCart.cpp -L/usr/lib -lmysqlcppconn
	g++ -Wall -I/usr/include/mysql-cppconn -oreview_cart ReviewCart.cpp -L/usr/lib -lmysqlcppconn
	g++ -Wall -I/usr/include/mysql-cppconn -oremove_from_cart RemoveFromCart.cpp -L/usr/lib -lmysqlcppconn
	g++ -Wall -I/usr/include/mysql-cppconn -oreview_claims ReviewClaims.cpp -L/usr/lib -lmysqlcppconn
	g++ -Wall -I/usr/include/mysql-cppconn -ocheckout CheckoutCart.cpp -L/usr/lib -lmysqlcppconn
	g++ -Wall -I/usr/include/mysql-cppconn -ohistory BoughtHistory.cpp -L/usr/lib -lmysqlcppconn
